
	/*
	 * This was file automatically generated by fixie.
	 * It contains a JavaScript array with the information to be passed to Lunr
	 * (https://lunrjs.com/) to provide a search feature via JavaScript.
	 */
	var searchDocuments = [{
		"id": "/about",
		"name": "About Fixie",
		"text": "about fixie the simplest blog engine that could possibly work"
	},{
		"id": "/index",
		"name": "Welcome to Fixie",
		"text": "welcome to fixie this is the home page"
	},{
		"id": "/blog/2022-12-08/two",
		"name": "Second",
		"text": "second this is another blog post"
	},{
		"id": "/blog/2020-11-19/one",
		"name": "One",
		"text": "one this is blog post"
	}];